# Site
repository: hmzhang48/hmzhang48.github.io
favicon: images/CV.png

# Content configuration version
version: 2

# Personal info
name: Haomin Zhang
title: HCI Student | Full-stack Developer
email: zhanghaomin9248@gmail.com
website: hmzhang48.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: hmzhang48
linkedin_username: hmzhang48

# Additional icon links
additional_links:
# - title: another link
#   icon: font awesome brand icon name
#   url: Link url

# About Section
# about_title: About Me
about_profile_image: images/Hermes.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Haomin Zhang and I am a **full-stack developer**. I am currently pursuing a **master** degree of **Human Computer Interaction** at **University College Dublin**.

  I am most proficient in: <mark>Typescript</mark>, <mark>Vue</mark>, <mark>Fastify</mark>, <mark>R</mark>, <mark>Tidyverse</mark>, <mark>Tidymodels</mark>, <mark>Python</mark>, <mark>Pandas</mark>, <mark>Fast.ai</mark>, <mark>Hugging Face</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Job Website
        # link:
        # link_text: 
        additional_links:
          - title: Job Website
            icon: fab fa-github
            url: github.com/hmzhang48/Job_Website
        quote: >
          A job portal for both job seekers and recruiters. 
        description: | # this will include new lines to allow paragraphs
          Constructed a **Single-page application** with reactive framework **Vue 3**, leveraging **Vue Router** for component navigation, **Pinia** for state management, and **Vite** as both a dev server and a build tool.

          Developed **RESTful APIs** with **Node.js** framework **Fastify 4**, utilizing **JSON Web Token** for authentication, **JSON schema** for validation, **Server-sent events** for notification, and **Drizzle ORM** to interact with relational database **PostgreSQL**.

      - layout: left
        border: weak
        title: Education App                                                                       
        # link:
        # link_text:
        additional_links:
          - title: Education App
            icon: fab fa-figma
            url: figma.com/file/iLDLrStzODMTF9zpo51nxd/HCI-Group-Design-challenge?type=design&node-id=0%3A1&mode=design&t=amks12qJMFFhwQpC-1
        quote: >
          Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all
        description: | # this will include new lines to allow paragraphs
          Constructed a high-fidelity prototype with **Figma**.
          
          Designed user interface following **Material Design 3** guidelines. 

      - layout: left
        border: weak
        title: Kaggle Competitions
        # link: 
        # link_text: 
        additional_links:
          - title: Quarto
            icon: fab fa-r-project
            url: hmzhang48.github.io/Statistics          
          - title: Colab
            icon: fab fa-python
            url: colab.research.google.com/drive/1WVvElujNORFvmCnUpjBkPMSq_fAkKOmc?usp=sharing
          - title: Colab
            icon: fab fa-python
            url: colab.research.google.com/drive/1-B7IMY0wdQfqYoZaJikgOa7ivWOOvhbX?usp=sharing
        quote: >
          Titanic - Machine Learning from Disaster & House Prices - Advanced Regression Techniques & Natural Language Processing with Disaster Tweets & Digit Recognizer
        description: | # this will include new lines to allow paragraphs
          Applied **machine learning** in **R** to analyze the Titanic dataset for **classification** and predict house prices through **regression**.

          Implemented **data visualization** and **feature engineering** with **Tidyverse**.

          Fitted and tuned **Random Forest** model for **classification** and **Boosted Trees** (**XGBoost**) model for **regression** with **Tidymodels**.
          
          Applied **deep learning** in **Python** to analyze Disaster Tweets for **text classification** and recognize digits through **image classification**.

          Implemented **data preprocessing** with **Pandas** and **Hugging Face Datasets**.
          
          Fine-tuned **AWD-LSTM (RNN)** model and **ResNext (CNN)** with **Fast.ai**.
          
          Fine-tuned **DeBERTa V3** model and **Swin V2** model with **Hugging Face Transformers**.

      - layout: left
        title: Data Journalism Report
        # link:
        # link_text:
        additional_links:
          - title: The Gaza Strip
            icon: fab fa-github
            url: hmzhang48.github.io/Gaza_Strip
        quote: >
          The Gaza Strip - from an open-air prison to an open-air graveyard
        description: | # this will include new lines to allow paragraphs
          Developed slides with HTML presentation framework **Reveal.js**.
          
          Designed HTML5 canvas charts utilizing charting library **Chart.js**.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: University College Dublin
        caption: Sep. 2023 - Sep. 2024 (Expected)
        sub_title: Master of Human Computer Interaction
        quote: >
          UCD is a leading research-intensive university in Ireland.
        description: | # this will include new lines to allow paragraphs
          **Modules**: UXD: User-Centered Design, Human Computer Interaction, Human Language Technologies, Creative & Interactive Media, Quantitative Data Analysis, Information Ethics, AI & Ethics

      - layout: left
        title: Communication University of China
        caption: Sep. 2010 - Jun. 2014
        sub_title: Bachelor of Radio and Television Engineering
        quote: >
          CUC is one of the China's key universities of "Project 211", directly administered by the Ministry of Education.
        description: | # this will include new lines to allow paragraphs
          **Modules**: Photography & Lighting Technology, Audio Engineering, TV Program Editing and Digital Compositing Technology, Art of TV Editing and Directing, Film & TV Editing Art, Digital TV Studio Technology

  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Programming**: HTML, CSS, JavaScript (TypeScript), Python, Go, R, SQL
      - **Design & Prototype**: Photoshop, Illustrator, Figma
      - **Video & Audio Editing**: Premiere, After Effect, Audition

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Shenzhen Media Group
        # link:
        # link_text:
        sub_title: Broadcasting Engineer
        caption: Jan. 2015 - Jun. 2023
        quote: >
          SZMG is a state media company based in Shenzhen, Guangdong province, China.
        description: | # this will include new lines to allow paragraphs
          Managed a broadcasting control system, maintaining annual gross downtime below **30** minutes for **8** consecutive years.

          Led my colleagues to rewrite a broadcasting manual, streamlining workflows and reducing over **30%** training time.

      - layout: left
        title: Beijing Huxiu Information Technology Co., Ltd.
        # link:
        # link_text:
        sub_title: Journalist & Editor
        caption: Jul. 2014 - Dec. 2014
        quote: >
          Huxiu is an information platform focusing on technology and innovation.
        description: | # this will include new lines to allow paragraphs
          Authored over **50** high-impact reports and articles on IT trends, reaching **hundreds of thousands** of readers.

          Audited over **20** daily article submissions for publication, maintaining editorial quality and reader engagement.

# Footer
footer_show_references: true
# references_title:

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
